/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "protocol.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(RldMessage, RldMessage, AUTO)


PB_BIND(RldInfo, RldInfo, AUTO)


PB_BIND(SetRldInfo, SetRldInfo, AUTO)


PB_BIND(SetRldInfo_Response, SetRldInfo_Response, AUTO)


PB_BIND(SetRldInfo_Request, SetRldInfo_Request, AUTO)



