/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_PROTOCOL_PB_HPP_INCLUDED
#define PB_PROTOCOL_PB_HPP_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RldInfo {
    int32_t id;
    int32_t flags;
    int32_t px;
    int32_t py;
} RldInfo;

typedef struct _SetRldInfo {
    char dummy_field;
} SetRldInfo;

typedef struct _SetRldInfo_Response {
    char dummy_field;
} SetRldInfo_Response;

typedef struct _Response {
    pb_size_t which_response;
    union {
        SetRldInfo_Response set_rld_info;
    } response;
} Response;

typedef struct _SetRldInfo_Request {
    bool has_info;
    RldInfo info;
} SetRldInfo_Request;

typedef struct _Request {
    pb_size_t which_request;
    union {
        SetRldInfo_Request set_rld_info;
    } request;
} Request;

typedef struct _RldMessage {
    char id[37];
    pb_size_t which_message;
    union {
        Request request;
        Response response;
    } message;
} RldMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Request_init_default                     {0, {SetRldInfo_Request_init_default}}
#define Response_init_default                    {0, {SetRldInfo_Response_init_default}}
#define RldMessage_init_default                  {"", 0, {Request_init_default}}
#define RldInfo_init_default                     {0, 0, 0, 0}
#define SetRldInfo_init_default                  {0}
#define SetRldInfo_Response_init_default         {0}
#define SetRldInfo_Request_init_default          {false, RldInfo_init_default}
#define Request_init_zero                        {0, {SetRldInfo_Request_init_zero}}
#define Response_init_zero                       {0, {SetRldInfo_Response_init_zero}}
#define RldMessage_init_zero                     {"", 0, {Request_init_zero}}
#define RldInfo_init_zero                        {0, 0, 0, 0}
#define SetRldInfo_init_zero                     {0}
#define SetRldInfo_Response_init_zero            {0}
#define SetRldInfo_Request_init_zero             {false, RldInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RldInfo_id_tag                           1
#define RldInfo_flags_tag                        2
#define RldInfo_px_tag                           3
#define RldInfo_py_tag                           4
#define Response_set_rld_info_tag                1
#define SetRldInfo_Request_info_tag              1
#define Request_set_rld_info_tag                 1
#define RldMessage_id_tag                        1
#define RldMessage_request_tag                   2
#define RldMessage_response_tag                  3

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_rld_info,request.set_rld_info),   1)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_request_set_rld_info_MSGTYPE SetRldInfo_Request

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,set_rld_info,response.set_rld_info),   1)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL
#define Response_response_set_rld_info_MSGTYPE SetRldInfo_Response

#define RldMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,request,message.request),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,response,message.response),   3)
#define RldMessage_CALLBACK NULL
#define RldMessage_DEFAULT NULL
#define RldMessage_message_request_MSGTYPE Request
#define RldMessage_message_response_MSGTYPE Response

#define RldInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, INT32,    flags,             2) \
X(a, STATIC,   SINGULAR, INT32,    px,                3) \
X(a, STATIC,   SINGULAR, INT32,    py,                4)
#define RldInfo_CALLBACK NULL
#define RldInfo_DEFAULT NULL

#define SetRldInfo_FIELDLIST(X, a) \

#define SetRldInfo_CALLBACK NULL
#define SetRldInfo_DEFAULT NULL

#define SetRldInfo_Response_FIELDLIST(X, a) \

#define SetRldInfo_Response_CALLBACK NULL
#define SetRldInfo_Response_DEFAULT NULL

#define SetRldInfo_Request_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              1)
#define SetRldInfo_Request_CALLBACK NULL
#define SetRldInfo_Request_DEFAULT NULL
#define SetRldInfo_Request_info_MSGTYPE RldInfo

extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Response_msg;
extern const pb_msgdesc_t RldMessage_msg;
extern const pb_msgdesc_t RldInfo_msg;
extern const pb_msgdesc_t SetRldInfo_msg;
extern const pb_msgdesc_t SetRldInfo_Response_msg;
extern const pb_msgdesc_t SetRldInfo_Request_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg
#define Response_fields &Response_msg
#define RldMessage_fields &RldMessage_msg
#define RldInfo_fields &RldInfo_msg
#define SetRldInfo_fields &SetRldInfo_msg
#define SetRldInfo_Response_fields &SetRldInfo_Response_msg
#define SetRldInfo_Request_fields &SetRldInfo_Request_msg

/* Maximum encoded size of messages (where known) */
#define Request_size                             48
#define Response_size                            2
#define RldInfo_size                             44
#define RldMessage_size                          88
#define SetRldInfo_Request_size                  46
#define SetRldInfo_Response_size                 0
#define SetRldInfo_size                          0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
