/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "trx.device.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GetBatteryStatus, GetBatteryStatus, AUTO)


PB_BIND(GetBatteryStatus_Request, GetBatteryStatus_Request, AUTO)


PB_BIND(GetBatteryStatus_Response, GetBatteryStatus_Response, AUTO)


PB_BIND(GetDeviceInfo, GetDeviceInfo, AUTO)


PB_BIND(GetDeviceInfo_Request, GetDeviceInfo_Request, AUTO)


PB_BIND(GetDeviceInfo_Response, GetDeviceInfo_Response, AUTO)



