/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRX_DEVICE_PB_HPP_INCLUDED
#define PB_TRX_DEVICE_PB_HPP_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GetBatteryStatus_Request {
    char dummy_field;
} GetBatteryStatus_Request;

typedef struct _GetBatteryStatus_Response {
    int32_t battery_level;
    bool isCharging;
} GetBatteryStatus_Response;

typedef struct _GetBatteryStatus {
    pb_size_t which_message;
    union {
        GetBatteryStatus_Request request;
        GetBatteryStatus_Response response;
        pb_callback_t error;
    } message;
} GetBatteryStatus;

typedef struct _GetDeviceInfo_Request {
    char dummy_field;
} GetDeviceInfo_Request;

typedef struct _GetDeviceInfo_Response {
    pb_callback_t device_id;
    pb_callback_t fw_version;
} GetDeviceInfo_Response;

typedef struct _GetDeviceInfo {
    pb_size_t which_message;
    union {
        GetDeviceInfo_Request request;
        GetDeviceInfo_Response response;
        pb_callback_t error;
    } message;
} GetDeviceInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GetBatteryStatus_init_default            {0, {GetBatteryStatus_Request_init_default}}
#define GetBatteryStatus_Request_init_default    {0}
#define GetBatteryStatus_Response_init_default   {0, 0}
#define GetDeviceInfo_init_default               {0, {GetDeviceInfo_Request_init_default}}
#define GetDeviceInfo_Request_init_default       {0}
#define GetDeviceInfo_Response_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define GetBatteryStatus_init_zero               {0, {GetBatteryStatus_Request_init_zero}}
#define GetBatteryStatus_Request_init_zero       {0}
#define GetBatteryStatus_Response_init_zero      {0, 0}
#define GetDeviceInfo_init_zero                  {0, {GetDeviceInfo_Request_init_zero}}
#define GetDeviceInfo_Request_init_zero          {0}
#define GetDeviceInfo_Response_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GetBatteryStatus_Response_battery_level_tag 1
#define GetBatteryStatus_Response_isCharging_tag 2
#define GetBatteryStatus_request_tag             1
#define GetBatteryStatus_response_tag            2
#define GetBatteryStatus_error_tag               3
#define GetDeviceInfo_Response_device_id_tag     1
#define GetDeviceInfo_Response_fw_version_tag    2
#define GetDeviceInfo_request_tag                1
#define GetDeviceInfo_response_tag               2
#define GetDeviceInfo_error_tag                  3

/* Struct field encoding specification for nanopb */
#define GetBatteryStatus_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,request,message.request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,response,message.response),   2) \
X(a, CALLBACK, ONEOF,    STRING,   (message,error,message.error),   3)
#define GetBatteryStatus_CALLBACK pb_default_field_callback
#define GetBatteryStatus_DEFAULT NULL
#define GetBatteryStatus_message_request_MSGTYPE GetBatteryStatus_Request
#define GetBatteryStatus_message_response_MSGTYPE GetBatteryStatus_Response

#define GetBatteryStatus_Request_FIELDLIST(X, a) \

#define GetBatteryStatus_Request_CALLBACK NULL
#define GetBatteryStatus_Request_DEFAULT NULL

#define GetBatteryStatus_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    battery_level,     1) \
X(a, STATIC,   SINGULAR, BOOL,     isCharging,        2)
#define GetBatteryStatus_Response_CALLBACK NULL
#define GetBatteryStatus_Response_DEFAULT NULL

#define GetDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,request,message.request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,response,message.response),   2) \
X(a, CALLBACK, ONEOF,    STRING,   (message,error,message.error),   3)
#define GetDeviceInfo_CALLBACK pb_default_field_callback
#define GetDeviceInfo_DEFAULT NULL
#define GetDeviceInfo_message_request_MSGTYPE GetDeviceInfo_Request
#define GetDeviceInfo_message_response_MSGTYPE GetDeviceInfo_Response

#define GetDeviceInfo_Request_FIELDLIST(X, a) \

#define GetDeviceInfo_Request_CALLBACK NULL
#define GetDeviceInfo_Request_DEFAULT NULL

#define GetDeviceInfo_Response_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   fw_version,        2)
#define GetDeviceInfo_Response_CALLBACK pb_default_field_callback
#define GetDeviceInfo_Response_DEFAULT NULL

extern const pb_msgdesc_t GetBatteryStatus_msg;
extern const pb_msgdesc_t GetBatteryStatus_Request_msg;
extern const pb_msgdesc_t GetBatteryStatus_Response_msg;
extern const pb_msgdesc_t GetDeviceInfo_msg;
extern const pb_msgdesc_t GetDeviceInfo_Request_msg;
extern const pb_msgdesc_t GetDeviceInfo_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GetBatteryStatus_fields &GetBatteryStatus_msg
#define GetBatteryStatus_Request_fields &GetBatteryStatus_Request_msg
#define GetBatteryStatus_Response_fields &GetBatteryStatus_Response_msg
#define GetDeviceInfo_fields &GetDeviceInfo_msg
#define GetDeviceInfo_Request_fields &GetDeviceInfo_Request_msg
#define GetDeviceInfo_Response_fields &GetDeviceInfo_Response_msg

/* Maximum encoded size of messages (where known) */
/* GetBatteryStatus_size depends on runtime parameters */
/* GetDeviceInfo_size depends on runtime parameters */
/* GetDeviceInfo_Response_size depends on runtime parameters */
#define GetBatteryStatus_Request_size            0
#define GetBatteryStatus_Response_size           13
#define GetDeviceInfo_Request_size               0
#define TRX_DEVICE_PB_HPP_MAX_SIZE               GetBatteryStatus_Response_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
