/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "trx.tracker.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Entity, Entity, AUTO)


PB_BIND(Position, Position, AUTO)


PB_BIND(SetEntity, SetEntity, AUTO)


PB_BIND(SetEntity_Request, SetEntity_Request, AUTO)


PB_BIND(SetEntity_Response, SetEntity_Response, AUTO)





