/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "trx.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(Error, Error, AUTO)


PB_BIND(TrxMessage, TrxMessage, AUTO)



